import type {
  BackgroundTheme,
  Planet,
  PresetKey,
  SolarTextureKey,
} from "./types";

export const TEXTURE_MAP: Record<SolarTextureKey, string> = {
  mercury: "/solar-system/2k_mercury.jpg",
  venus_surface: "/solar-system/2k_venus_surface.jpg",
  earth: "/solar-system/2k_earth_daymap.jpg",
  moon: "/solar-system/2k_moon.jpg",
  mars: "/solar-system/2k_mars.jpg",
  ceres: "/solar-system/2k_ceres_fictional.jpg",
  eris: "/solar-system/2k_eris_fictional.jpg",
  haumea: "/solar-system/2k_haumea_fictional.jpg",
  makemake: "/solar-system/2k_makemake_fictional.jpg",
  jupiter: "/solar-system/2k_jupiter.jpg",
  saturn: "/solar-system/2k_saturn.jpg",
  saturn_ring: "/solar-system/2k_saturn_ring_alpha.png",
  uranus: "/solar-system/2k_uranus.jpg",
  neptune: "/solar-system/2k_neptune.jpg",
  sun: "/solar-system/2k_sun.jpg",
  stars: "/solar-system/2k_stars.jpg",
  stars_milky_way: "/solar-system/2k_stars_milky_way.jpg",
};

export const GLOW_COLORS: Partial<Record<SolarTextureKey, string>> = {
  mercury: "rgba(139,137,137,0.1)",
  venus_surface: "rgba(204,119,34,0.12)",
  earth: "rgba(65,105,225,0.15)",
  moon: "rgba(200,200,200,0.1)",
  mars: "rgba(205,92,92,0.12)",
  ceres: "rgba(184,156,122,0.1)",
  eris: "rgba(217,232,245,0.12)",
  haumea: "rgba(181,220,236,0.12)",
  makemake: "rgba(190,118,82,0.12)",
  jupiter: "rgba(199,165,117,0.12)",
  saturn: "rgba(224,205,167,0.1)",
  uranus: "rgba(0,206,209,0.12)",
  neptune: "rgba(30,144,255,0.15)",
};

export const DEFAULT_PLANETS: Planet[] = [
  {
    id: "mercury",
    name: "Mercury",
    textureKey: "mercury",
    size: 10,
    orbitSize: 145,
    duration: 6,
    type: "Rocky",
    temp: "440 K",
    desc: "Smallest and closest planet to the Sun, heavily cratered and experiencing extreme temperatures.",
  },
  {
    id: "venus",
    name: "Venus",
    textureKey: "venus_surface",
    size: 18,
    orbitSize: 200,
    duration: 10,
    type: "Rocky",
    temp: "737 K",
    desc: "A choking greenhouse world covered in thick yellow-white clouds of sulfuric acid.",
  },
  {
    id: "earth",
    name: "Earth",
    textureKey: "earth",
    size: 20,
    orbitSize: 270,
    duration: 15,
    type: "Habitable",
    temp: "288 K",
    desc: "Our home planet. The only world known to harbor life, with vast oceans and a protective atmosphere.",
    hasMoon: true,
  },
  {
    id: "mars",
    name: "Mars",
    textureKey: "mars",
    size: 13,
    orbitSize: 345,
    duration: 22,
    type: "Rocky",
    temp: "210 K",
    desc: "The red planet, covered in iron-rich dust, thin carbon dioxide atmosphere, and polar ice caps.",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    textureKey: "jupiter",
    size: 56,
    orbitSize: 460,
    duration: 35,
    type: "Gas Giant",
    temp: "165 K",
    desc: "The largest planet in our solar system, famous for its Great Red Spot and turbulent storms.",
  },
  {
    id: "saturn",
    name: "Saturn",
    textureKey: "saturn",
    size: 48,
    orbitSize: 580,
    duration: 48,
    type: "Gas Giant",
    temp: "134 K",
    desc: "A gas giant adorned with a spectacular, broad ring system composed of icy particles.",
    hasRings: true,
  },
  {
    id: "uranus",
    name: "Uranus",
    textureKey: "uranus",
    size: 32,
    orbitSize: 685,
    duration: 62,
    type: "Ice Giant",
    temp: "76 K",
    desc: "A pale cyan ice giant with a unique 98-degree axial tilt, causing extreme seasons.",
    hasRings: true,
  },
  {
    id: "neptune",
    name: "Neptune",
    textureKey: "neptune",
    size: 30,
    orbitSize: 790,
    duration: 76,
    type: "Ice Giant",
    temp: "72 K",
    desc: "A deep blue, windy ice giant. The most distant planet from the Sun.",
  },
];

export const PRESETS: Record<PresetKey, Planet[]> = {
  full: DEFAULT_PLANETS,
  inner: DEFAULT_PLANETS.slice(0, 4),
  outer: DEFAULT_PLANETS.slice(4),
  empty: [],
};

export const TEXTURE_OPTIONS: { key: SolarTextureKey; name: string }[] = [
  { key: "mercury", name: "Mercury" },
  { key: "venus_surface", name: "Venus" },
  { key: "earth", name: "Earth" },
  { key: "mars", name: "Mars" },
  { key: "jupiter", name: "Jupiter" },
  { key: "saturn", name: "Saturn" },
  { key: "uranus", name: "Uranus" },
  { key: "neptune", name: "Neptune" },
  { key: "moon", name: "Moon" },
  { key: "ceres", name: "Ceres" },
  { key: "eris", name: "Eris" },
  { key: "haumea", name: "Haumea" },
  { key: "makemake", name: "Makemake" },
];

export const TYPE_OPTIONS = [
  "Rocky",
  "Habitable",
  "Gas Giant",
  "Ice Giant",
  "Dwarf Planet",
  "Lava",
  "Exotic",
];

export const SUN: Planet = {
  id: "sun",
  name: "The Sun",
  textureKey: "sun",
  size: 96,
  orbitSize: 0,
  duration: 0,
  type: "Yellow Dwarf Star",
  temp: "5,778 K",
  desc: "The yellow dwarf star at the gravitational heart of our system. It comprises roughly 99.8% of the system's total mass.",
};

export const DEFAULT_BACKGROUND_THEME: BackgroundTheme = "stars_milky_way";
export const AMBIENT_AUDIO_URL = "/solar-system/space-ambient.mp3";
export const DEFAULT_AMBIENT_VOLUME = 0.2;
